### ISSUE TITLE
New UI for CBA

### ISSUE THREAD

**Issue by Manvel** [browser-automation/cba#99]
# Background

According to the review comment analysis of the past 7 years, apparently most of the comments were about bad UI/UX: 

<img width="604" alt="Screen Shot 2021-03-26 at 5 23 28 PM" src="https://user-images.githubusercontent.com/716969/112645882-fd6cd880-8e57-11eb-8b88-f7a11004fc74.png">

In order to fix that, we have come up with but more modern look for the CBA, as you can see below:

<img width="556" alt="Screen Shot 2021-03-26 at 5 25 47 PM" src="https://user-images.githubusercontent.com/716969/112646207-50469000-8e58-11eb-8c75-9d535bf9481f.png">

# What to change
In order to get there we will need to:
- [ ] Add [buttons and kebab menu support for cba-table row](https://github.com/browser-automation/cba-components/issues/44).
- [ ] Add [Selectbox support to the cba-table component](https://github.com/browser-automation/cba-components/issues/43).
- [ ] Add [Buttons and kebab menu support for cba-list](https://github.com/browser-automation/cba-components/issues/45)
- [ ] Create [cba-select component](https://github.com/browser-automation/cba-components/issues/42)
- [ ] Update the UI according and functionality to the screenshot above (issue(s) TBA...)

**Comment by WebStarDev** [comment]
Interesting Job
